name: projectoneuniversity
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  dartz: ^0.10.1
  flutter_animate: ^4.2.0
  flutter_launcher_icons: ^0.13.1
  flutter_otp_text_field: ^1.1.1
  flutter_screenutil: ^5.9.0
  google_nav_bar: ^5.0.6
  google_sign_in: ^6.2.1
  http: ^0.13.6
  lottie: ^2.6.0
  path: ^1.8.3
  shared_preferences: ^2.2.1
  show_up_animation: ^2.0.0
  flutter_paypal_checkout: ^1.0.1
  jiffy: ^6.2.2
  image_picker: ^1.0.4
  url_launcher: ^6.2.6
  popover: ^0.2.9
  flutter_rating_bar: ^4.0.1
  fl_chart: ^0.63.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
